### ISSUE TITLE
Index

### ISSUE THREAD

**Issue by 123pranjal** [agarwalneha24/Chat-Application#7]
Error

**Comment by agarwalneha24** [comment]
<meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />

**Comment by agarwalneha24** [comment]
Done

**Comment by agarwalneha24** [comment]
Angular bracket closed
