### ISSUE TITLE
Features Should be written in documentation properly

### ISSUE THREAD

**Issue by almique** [agarwalneha24/Chat-Application#9]
- Add what frameworks are used 
- add tags in documentation

**Comment by agarwalneha24** [comment]
Create React App.
Profile => Component depicts the randomly generted main user avatar, name.
Contact => Component depicts the randomly generated conatact list (atmost 15) and their recent messages.
MessageBox => Component shows the structure the whole message box and messages (atmost 50 per contact) are sorted according to date and time.
Message => Components show the structure of each message.
Input => Component for sending an input message, Things to note here is until we don't type, microphone icon is shown on right, as soon we start typing it changes to send button. Also we can send message by the stroke of Enter Key, but we can't send an empty message.
